# Generated by Django 3.0.2 on 2020-03-06 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardapporigin', '0006_auto_20200306_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardmodel',
            name='read',
            field=models.IntegerField(default=0),
        ),
    ]
