# Generated by Django 3.0.2 on 2020-03-10 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardapporigin', '0008_auto_20200307_0458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardmodel',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
