# Generated by Django 3.0.2 on 2020-03-31 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boardapporigin', '0014_good'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Good',
            new_name='Koushin',
        ),
    ]
